pool:
  vmImage: 'windows-2022'

steps:
- task: UseDotNet@2
  displayName: 'Install .net6 runtime (required for running Unit Tests only)'
  inputs:
    packageType: 'runtime'
    version: '6.x'

- task: VSBuild@1
  displayName: Build
  inputs:
    configuration: 'Release'
    msbuildArgs: '/restore'

- task: VSTest@2
  displayName: Test
  inputs:
    configuration: 'Release'
